name: GitHub Actions React Home Example
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - master
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm i
      - name: build project
        run: npm run build:prod
      - name: linting typescript
        run: npm run lint:ts
      - name: linting-styles
        run: npm run lint:scss
      - name: testing unit
        run: npm run test:unit
